# API Configuration
NEXT_PUBLIC_API_URL=https://api.airiam.com
NEXT_PUBLIC_WS_URL=wss://api.airiam.com

# Authentication
NEXTAUTH_URL=https://rag.airiam.com
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXT_PUBLIC_JWT_SECRET=${JWT_SECRET}

# OAuth Providers
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}

# Feature Flags
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ENABLE_CLOUD_STORAGE=true
NEXT_PUBLIC_ENABLE_MULTI_TENANT=true

# Theming
NEXT_PUBLIC_DEFAULT_THEME=light
